### ISSUE TITLE
Issues from Ale 240907

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#1]
Test on 240829 debug on

- [x]  1. When Pico reset needed, Pico connected and error at the same time

- [x] #2

- [x] #3

- [x] #4

- [x] #5

- [x] #6

- [x] #7

- [x] #8

- [x] #9

- [x] #10

- [x] #11

- [x] #12

- [x] #13

- [x] #14

- [x] #15

- [x] #16

**Comment by Gavin-Perry** [comment]
Issues 2-16 broken out to their own issue numbers.
For this issue I'm not seeing it any more. Do you? Under what exact conditions? (Pico state, App start or restart?)

**Comment by Gavin-Perry** [comment]
Changed back to uialert() with pause code to fix hidden alert.

**Comment by alessli** [comment]
I believe even issue number one is fixed now. Therefore, i think we can close it.

**Comment by Gavin-Perry** [comment]
Got these first 16 finished. Phew!
