### ISSUE TITLE
if i click pause, then wait, restart with a new session, and then pause again i have the button saying 'ready' but in the meantime the code is looping through trials.

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#12]
This looks like it may be a real bug to be investigated (Right now I'm skimming and doing the easy ones)

**Comment by alessli** [comment]
In the version 13.
I paused, and started a new session. However, starting an all new session gets me to a situation where it says 'the DefaultStimList.txt' doesn't exist, and i can't click on the 'load input file' to change the folder.
I took a screenshot and attached it here, let me know if you can't see it.

![Capture](https://github.com/user-attachments/assets/cd65efc2-970f-44d9-8f35-a40962be5cdf)
![Capture](https://github.com/user-attachments/assets/cd65efc2-970f-44d9-8f35-a40962be5cdf)

**Comment by Gavin-Perry** [comment]
Folder issue fixed in v2x
