### ISSUE TITLE
No Count Errors on, Error received not corrected

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#21]
Running with the NoCountErr flag true and the subject only picks Air which is wrong, but it won't count so Pico keeps looking for a correct choice. 
Correct choice made before timeout - no problem reward is given.
No more choices detected so it's now an ignored trial. (-1)
If Repeat until correct is also on then stay on that trial until it's done right.
Without RepCor on then the trial is set as -1 and will be repeated later.

Do you need any information that this "ignored" trial actually had a failed choice (some code other than F or -1) or is this fine as is?

**Comment by Gavin-Perry** [comment]
Here is another related issue:
NoCountErrors is on, there are alternating licks left and right.
Since we are not counting errors does it count as a correct choice once the number of licks is enough, even though there were bad licks in the burst? Or does the lick count for a burst reset when the other side is touched regardless of the NoCountError status? So that enough licks in a row are needed on the correct side to count as a correct response.

**Comment by Gavin-Perry** [comment]
Please respond to NCE issues here

**Comment by alessli** [comment]
1. "Do you need any information that this "ignored" trial actually had a failed choice (some code other than F or -1) or is this fine as is?". No, I don't need any information, just an F is fine.
2. "Or does the lick count for a burst reset when the other side is touched regardless of the NoCountError [NCE] status? " Correct. Regardless of the NCE status, the lick on the opposite side resets the burst. In other words, NCE ignores the wrong _responses_, but a _response_ to be defined as such has to always be N consecutive licks on the same side within the time T.

**Comment by Gavin-Perry** [comment]
Okay that's an easy change I can make in the Pico

**Comment by Gavin-Perry** [comment]
Please verify that it's fixed. I can reopen this issue (21) if there is still a problem.
