### ISSUE TITLE
Sorting AA and BB

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#26]
This still needs to be done. Should be in V27

**Comment by Gavin-Perry** [comment]
Merge with #46

**Comment by Gavin-Perry** [comment]
Which way?
% Update graph? Only if Rewarded or Failed  (not ignored trials)
%    if (app.RewardGiven == true) || (~app.RepCor && app.IsError)
     if ~ app.IgnoredTrial  % include failed each time or update on success???
        UpdateGraph(app,app.bChosen);
    end

**Comment by alessli** [comment]
Please re-open.
Sorting AA and BB trials has a problem.
I used the following list: 
1	4	0
1	5	-2
1	4	1
1	3	2
1	2	5
1	-1	3
1	1	8

Bu the order on x axis is not correct. In the following screenshot, the two offers on the yellow circles should be flipped, so the offers on the red circles. 
![graph_sort](https://github.com/user-attachments/assets/edc42b87-428a-4a9e-b6e9-53186b5e2ee7)

**Comment by Gavin-Perry** [comment]
Not just < but <=0 to be AA or BB. Proper sort order (Stim Input)
1	4	0
1	5	-2
1	4	1
1	3	2
1	2	5
1	1	8
1	-1	3

**Comment by Gavin-Perry** [comment]
If you like v33 you can  comment OK it so I can close it.  (I'll search for issues with OK in comments)

**Comment by alessli** [comment]
perfect, you can close it!
