### ISSUE TITLE
Problem with the sequence of the trial are presented. 

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#33]
In some cases, after the first iteration of all trials, the code present stimuli that already had a valid response, overwriting the previous outcome.

**Comment by alessli** [comment]
in another instance, I run multiple iterations, last trial without a response was -5 1 L. I licked on the right side, received 1B but code instead of finishing the session presented me that trial again.

**Comment by Gavin-Perry** [comment]
Fixed in v28 should still be fine in v29

**Comment by alessli** [comment]
Agree.
