### ISSUE TITLE
Not the full list of trial is presented

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#34]
Paused a session while i was on the 6th trial out of 8, started an all new, but now code only presents trials 6,7 and 8. I completed the three trials, code says it is finished, but it still presenting offers. I hear the solenoids, but on the GUI nothing happens.

**Comment by alessli** [comment]
After this problem i tried to close the software but it doens't let me do it. Kill me doesn't work either.

**Comment by Gavin-Perry** [comment]
Test with v29 I think this has been resolved.

**Comment by alessli** [comment]
confirmed.
