### ISSUE TITLE
Error on a new session

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#35]
Started a new session, loaded a list of trials, after loading i changed one trial type, randomized again, started and the software crashed.
![Error1_commandWindow 1](https://github.com/user-attachments/assets/44f18186-1556-4fdf-bcd2-72acc9c3ba52)

**Comment by Gavin-Perry** [comment]
Mostly works but I think there is still an occasional crash. Since the program disappears it's hard to track done. Post the Stim file used and results created into /NewSessionCrash

**Comment by Gavin-Perry** [comment]
Similar issue to #50 You can't change a trial to a new type

**Comment by alessli** [comment]
ok, so to make sure i understand, changes are only allowed as long as each trial type (AA, BB, AB, AB0, A0B) remains withing its category. am i correct?

**Comment by Gavin-Perry** [comment]
More than that see #50 You can't change things in the Trials table, do it in the Input table. If you need certain order use TRAINING
