### ISSUE TITLE
Code didn't finish the session (with screenshots)

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#37]
Did few iterations, finished last trial, main button went in 'finish' mode, but ketp presenting more trials, changed some of the responses on the other trials and then had an error.
![Error12a 1](https://github.com/user-attachments/assets/189d165d-8fe9-480a-acfd-f58b369e360c)
![Error12b 1](https://github.com/user-attachments/assets/60fa2e8a-1ead-4d0e-886c-dd830b151552)
![Error12c 1](https://github.com/user-attachments/assets/99bb4ec9-7932-4e6d-8807-c68e377f9c32)
![Error12d 1](https://github.com/user-attachments/assets/cacc5014-5588-4436-97d6-f8d0e40471cf)
![Error12a_commandWindow 1](https://github.com/user-attachments/assets/dc00dce0-0f59-44a0-bfe2-c52ed4748a7b)
![Error12b_commandWindow 1](https://github.com/user-attachments/assets/8a5c71cb-e53a-4f08-85ce-36876f601d19)

**Comment by Gavin-Perry** [comment]
Fixed in v27  fully tested by Gavin in v29
 please check and reopen issue if there is still a problem

**Comment by alessli** [comment]
Initial testing in v 30. Problem seems fixed, will close it for now.
