### ISSUE TITLE
Sorting  AA AB BB for the graph

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#44]
I'm working on the AA AB BB sorting and I can't be sure I have it right.
Here is my test Input table after sorting. I left the math in the last column so you can see my sort values.
Is right or . . . what's wrong
  REP     '#A   '#B    sort value
     1       -1       3           -3
     1       -2       5         -2.5
     1        3      -2     -0.66667
     1        2      -5         -0.4
     1        4      -1        -0.25
     1        5       0            0
     1        0      -8            0
     1        4       1         0.25
     1        3       2      0.66667
     1       -3       2          1.5
     1        2       5          2.5
     1        1       3            3
     1        1       3            3
     1       -4       1            4
     1        0       3           21
     1       -3       0           21
     1       -5       0           23
     1        0       8           26
Here's the code I used:
            for ii = 1:sz
                aVal = app.StimInputTable.Data.Var2(ii);
                bVal = app.StimInputTable.Data.Var3(ii);
% check sort for neg values                
                if aVal < 0  % this is BB trial
% BB has a negative value for A  -> #A is the smaller of 2 B's
                   if abs(aVal) > bVal % swap so #A is smaller
                       tmp = abs(aVal);
                       aVal = bVal;
                       bVal = tmp;
                   end
                end
                if bVal < 0  % AA trial
% AA has a negative value for B  -> #A is largest of the 2                    
                   if aVal < abs(bVal) % swap so #A is smaller
                       tmp = abs(aVal);
                       aVal = bVal;
                       bVal = tmp;
                   end                    
                end

% Assign values that will put them in order for graph %B vs B/A
% They should sort OK since A and B properly set
% Just deal with A=0 for infinity
                if aVal == 0
% Put at the end of the table in B order (Add sz to be sure it's at the bottom)
                    app.StimInputTable.Data.Var4(ii) = bVal + sz;
                else  
                    app.StimInputTable.Data.Var4(ii) = bVal/aVal;
                end
            end

Thanks

**Comment by alessli** [comment]
The list should be organized as follow:
First, on the left we insert offers with only A (i.e, A>0 vs 0, or A vs A). These offers are organized by the absolute delta offer in a decreasing fashion. For offers with the same delta, the offer with the highest absolute value should go first.
Second, with the offers with both A and B (A>0. B>0). These offers are organized by the ratio of quantityB/quantityA increasing. Offers with the same ratio should be organized with the smallest B first.
Third, we have offers with only B  (i.e, B>0 vs 0, or B vs B). These offers are organized by the absolute delta offer in an increasing fashion. For offers with the same delta, you take the highest value for each offer, and the offer withe the lowest, absolute value should go first.

In your list, my algorithm should organize as the below. Please note, the first, second and third columns are exactly as in your list. But the fourth column is an ordinal number that tells you which offer goes first (1) on the left, and which goes last on the right (18).
1 -1 3 12
1 -2 5 16
1 3 -2 8
1 2 -5 4
1 4 -1 3
1 5 0 2
1 0 -8 1
1 4 1 9
1 3 2 10
1 -3 2 11
1 2 5 2 5
1 1 3 6
1 1 3 7
1 -4 1 15
1 0 3 13
1 -3 0 14
1 -5 0 17
1 0 8 18

**Comment by Gavin-Perry** [comment]
Line 11
1 2 5 2 5   is it 2 or 5?

**Comment by Gavin-Perry** [comment]
I've sorted what you put in by the numbers (tab separated)
So I realize that some items would never be in a real list like the first one which is really just 8 0
But I might as well sort all possible entries, which is what I was trying for. Every thing possible, including repeats (1 3  for 6 and 7)
For the fisrt column I examined the - signs and assigned them to trial types: A0, AA, AB, BB, B0
No. 8  seems to be out of order
 _A>0 vs 0, or A vs A). These offers are organized by the absolute delta offer in a decreasing fashion. For offers with the same delta, the offer with the highest absolute value should go first._

13 and 14 are the same (B 0), and 15 and 16 have the same delta (3)
_For offers with the same delta, you take the highest value for each offer, and the offer with the lowest, absolute value should go first._  Got it...

 could you please verify our example list now sorted
ID 	 A 	 B 	 Sort order
A 0 	 0 	 -8 	 1  == 8 0   highest first
A 0 	 5 	 0 	 2
AA 	 4 	 -1 	 3  delta 2
AA 	 2 	 -5 	 4  delta 1
AB 	 2 	 5 	 5
AB 	 1 	 3 	 6
AB 	 1 	 3 	 7
AA 	 3 	 -2 	 8  Out of order delta 1 should be between 4 and 5?
AB 	 4 	 1 	 9
AB 	 3 	 2 	 10
BB 	 -3 	 2 	 11
BB 	 -1 	 3 	 12
B 0 	 0 	 3 	 13
B 0 	 -3 	 0 	 14
BB 	 -4 	 1 	 15
BB 	 -2 	 5 	 16
B 0 	 -5 	 0 	 17
B 0 	 0 	 8 	 18 == highest last

**Comment by Gavin-Perry** [comment]
Rewrote the sort algorithm as follows:

                switch true % means that first case that evaluates to true is used
                    case aVal < 0  % == BB trial give higher sort orders
                       delta =  abs(abs(aVal) - bVal); % make positive delta
                       app.StimInputTable.Data.Var4(ii) = delta + 20;

                    case bVal < 0  % == AA trial these go first so give - sort orders
                        delta =  abs(abs(bVal) - aVal); % make positive delta
                        % bigger delta gets lower sort order
                        app.StimInputTable.Data.Var4(ii) =  -20 - delta;

                    case aVal == 0  % == B 0 trial
% Put at the end of the table in B order (Add 20 to be sure it's at the bottom)
                        app.StimInputTable.Data.Var4(ii) = bVal + 20;

                    case bVal == 0  % == A 0, use - numbers to sort
                        app.StimInputTable.Data.Var4(ii) = aVal - 20;

                    otherwise  % with A and B offers use ratio 
        % will be >0 & <1 fraction if A is bigger
        % up to max B/1 if B is bigger (no B bigger than 16????  so used 20 above
                        app.StimInputTable.Data.Var4(ii) = ...
                            bVal/aVal +  bVal/100;   % add increment so smallest B first
                end
            end

I've added a couple of cases to get same deltas
Index|A|B| sort calculation
1 | 0 | -8 | -28
2 | 4 | -1 | -23
3 | 2 | -5 | -23
4 | 3 | -2 | -21
5 | 5 | 0 | -15
6 | 4 | 1 | 0.26
7 | 3 | 2 | 0.68667
8 | 2 | 3 | 1.53
9 | 3 | 5 | 1.7167
10 | 2 | 5 | 2.55
11 | 1 | 3 | 3.03
12 | 2 | 8 | 4.08
13 | -3 | 2 | 21
14 | -1 | 3 | 22
15 | 0 | 3 | 23
16 | -3 | 0 | 23
17 | -4 | 1 | 23
18 | -2 | 5 | 23
19 | -5 | 0 | 25
20 | 0 | 8 | 28

**Comment by alessli** [comment]
> Line 11 1 2 5 2 5 is it 2 or 5?

5

**Comment by alessli** [comment]
> I've sorted what you put in by the numbers (tab separated) So I realize that some items would never be in a real list like the first one which is really just 8 0 But I might as well sort all possible entries, which is what I was trying for. Every thing possible, including repeats (1 3 for 6 and 7) For the fisrt column I examined the - signs and assigned them to trial types: A0, AA, AB, BB, B0 No. 8 seems to be out of order _A>0 vs 0, or A vs A). These offers are organized by the absolute delta offer in a decreasing fashion. For offers with the same delta, the offer with the highest absolute value should go first._
> 
> 13 and 14 are the same (B 0), and 15 and 16 have the same delta (3) _For offers with the same delta, you take the highest value for each offer, and the offer with the lowest, absolute value should go first._ Got it...
> 
> could you please verify our example list now sorted ID A B Sort order A 0 0 -8 1 == 8 0 highest first A 0 5 0 2 AA 4 -1 3 delta 2 AA 2 -5 4 delta 1 AB 2 5 5 AB 1 3 6 AB 1 3 7 AA 3 -2 8 Out of order delta 1 should be between 4 and 5? AB 4 1 9 AB 3 2 10 BB -3 2 11 BB -1 3 12 B 0 0 3 13 B 0 -3 0 14 BB -4 1 15 BB -2 5 16 B 0 -5 0 17 B 0 0 8 18 == highest last



A0 0 -8 1 == 8 0 highest first
A0 5 0 2
AA 4 -1 3 delta 2
AA 2 -5 4 delta 1
AA 3 -2 5 Out of order delta 1 should be between 4 and 5?
AB 4 1 6
AB 3 2 7
AB 2 5 8
AB 1 3 9
BB -3 2 10
BB -1 3 11
B0 0 3 12
B0 -3 0 13
BB -4 1 14
BB -2 5 15
B0 -5 0 16
B0 0 8 17 == highest last

First change, AA trials can't be after any AB (or bb trials). Yours 8 is now 5.
Second change, your trials 6 and 7 are the same offers. that won't happen, so i removed it.
Third change, i adjusted the AB trialas. ratio of B to A is increasing (not A to B, so it' the ratio of third column to second column in this list)

**Comment by alessli** [comment]
a typical list would be [rep, #A, #B]:

7 4 0
7 4 -1
7 2 0
10 5 2
10 3 3
10 2 3
10 1 4
10 1 7
7 0 2
7 -1 3
7 0 4

**Comment by Gavin-Perry** [comment]
Using this
1 4 0
1 4 -1
2 2 0
1 5 2
1 3 3
1 2 3
1 1 5
1 1 8
2 0 2
2 -1 3
1 0 8

So levels file doesn't need to change

**Comment by Gavin-Perry** [comment]
Check with V29 I think we're ready to close this issue

**Comment by alessli** [comment]
With V29 matlab and v28 info, if load your 'StimListAABB.txt', i get this error:
![image](https://github.com/user-attachments/assets/d253f662-0a7e-4984-ad69-517026bc119e)

**Comment by alessli** [comment]
please see issue #26 and my last comment in there. tested on v30

**Comment by Gavin-Perry** [comment]
Fixed in v33 see #26
