### ISSUE TITLE
Scoring AA and BB trials

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#46]
For AA or BB the larger must be chosen for a reward to be given. Is it stronger odor (OdorL > OdorR) or more drops (RewA < RewB) that is the deciding factor. I realize that in order to make sense they should be the same thing. If a weaker odor gave more drops that would be very confusing; but the software needs to know which to use to make the choice.

**Comment by alessli** [comment]
Agree. Quantity and concentration are monotonically related, therefore within AA or BB trials, the highest concentration is a proxy for the correct response.

**Comment by alessli** [comment]
For AA trials, lower A scores as B. For BB trials, lower B scores as A.

**Comment by Gavin-Perry** [comment]
Lower AA scores as B, so he should pick the smaller amount for it to be B?
In other word A is the preferred choice not B
That's weird even if it makes some theoretical sense.

**Comment by alessli** [comment]
Scoring is good in v31.
For reference:
- in trials AA and AB0, B in the graph is a proxy for mistakes.
- in trials BB and A0B, A in the graph is a proxy for mistakes.

**Comment by Gavin-Perry** [comment]
Got it. It makes sense now
