### ISSUE TITLE
Problem with choice waiting time (CWT)

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#51]
I set licking wait time to 0.5, but when i time it using a stop watch, and time for how long the 'wait' lamp is on, i am constantly at ~1.8-1.9 s. When CWT is at 2 s, i score  around ~3.5 s. When I set CWT at 4, i measure ~5.5s. In essence, there is a delay of ~1.5s.

**Comment by Gavin-Perry** [comment]
I'm not seeing that. The wait time starts with W and if no responses are given it will end at X
I set it for 4 seconds
F	13739886
W	13740087
X	13744087
3 seconds:
W	13320475
X	13323475
2 seconds:
F	13445777  Odor off, 200ms of tone
W	13445978   Wait starts
X	13447978  Wait ends

**Comment by Gavin-Perry** [comment]
Done. No light on until CWT starts. Odor light goes off at 'F', end of odor period but light doesn't come on until 'W'  2 second tone, 2.5sec CWT
F	14445424              Odor light off
W	14447425              Wait light on
X	14449925             Wait light off
