### ISSUE TITLE
Extra MC and 2p files created

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#52]
When i run a session, pause, start an all new, I input the mouse name, the stim list, and the res folder, that creates the .m result and the 2p result. But since i have to click again on 'finished' to start over, that (rightfully) creates new outputs.

**Comment by Gavin-Perry** [comment]
Oops, shouldn't create those files until the session starts. Not a fatal error but I'll fix it.

**Comment by Gavin-Perry** [comment]
Fixed in v32 allong with some other similar errors. There are a lot of paths through all the choices. Probably need to make a map!
