### ISSUE TITLE
Repeat until correct doesn't work on a second pass of trials

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#53]
If i start a session with RUC off, and after the first iteration of trials i turn RUC on, RUC doesn't work.

**Comment by Gavin-Perry** [comment]
I had multiple separate passes through the list and forgot RUC on the second pass.
I'll clean up the code to do it all in one place

**Comment by Gavin-Perry** [comment]
Fixed in v32 no changes to Pico so keep 31 for that.
