### ISSUE TITLE
Crash during the  code execution on v31

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#54]
First test with v31 and crashed during the execution.
All the parameters, and the error on the screenshots below.
![image](https://github.com/user-attachments/assets/530120b2-1e31-4459-bc06-000cfbdc4be2)

![image](https://github.com/user-attachments/assets/66cb5acc-ae20-4679-8ba7-69339dc950c2)

![image](https://github.com/user-attachments/assets/b89ab693-d7a4-4071-ab2e-933cd570038c)

**Comment by Gavin-Perry** [comment]
Pico wasn't properly connected. Once the error of not finding the serial port has happened then all following errors are meaningless. Did you try it again? Try v32  I didn't make any changes that would cause this but there are other fixes in 32 worth having. (RUC error)

**Comment by alessli** [comment]
OK, I will keep testing and let you know if I see it again.

**Comment by Gavin-Perry** [comment]
Haven't see this recently and we are now up to v38. Open a new issue if you see anything similar again.
