### ISSUE TITLE
Crashed after stop session and start a new one

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#66]
I was running a session in 'training mode', pressed stop, after 'stopping', pressed 'stop' again, and then clicked the main button to start a new one. The software crashed.

**Comment by Gavin-Perry** [comment]
I can't recreate this error with what you provide. Try in v44 and list specific steps to get it to crash and the error message in the command window that results.

**Comment by Gavin-Perry** [comment]
Not seeing any more after v50
