### ISSUE TITLE
The number of licks, should be applied to both detect correct and wrong responses. Now it does only for determine the correct response, but it gives error as soon as the animal touches the side with 0

### ISSUE THREAD

**Issue by Gavin-Perry** [Gavin-Perry/OdorChoice#7]
OH! So hitting the wrong side once isn't wrong until he commits by licking the Number of Lick times.
I had thought that an error wouldn't need to be repeated to be an error. A quick test lick is allowed eh?
That's a Pico issue I will fix.

**Comment by Gavin-Perry** [comment]
Please clarify when to count licks and errors. Is everything that happens before CWT ignored?
i.e during ITI, Odor presentation and Tone any licking is allowed and I start checking at start of CWT.
Licking 0 (air) side during eg. odor on is fine?

**Comment by Gavin-Perry** [comment]
See issue #17 about the different kinds of lick behaviors i.e. Licking to get a reward and licking up the reward drop.

**Comment by Gavin-Perry** [comment]
Lick bursts detected with burst parameters settable. Only NCE need clarifying.

**Comment by alessli** [comment]
What clarification do you need for NCE?

**Comment by Gavin-Perry** [comment]
All clear and should be correct now
